MiNiFi Config Version: 3
Flow Controller:
  name: minifi
  comment: ''
Core Properties:
  flow controller graceful shutdown period: 10 sec
  flow service write delay interval: 500 ms
  administrative yield duration: 30 sec
  bored yield duration: 10 millis
  max concurrent threads: 1
  variable registry properties: ''
FlowFile Repository:
  partitions: 256
  checkpoint interval: 2 mins
  always sync: false
  Swap:
    threshold: 20000
    in period: 5 sec
    in threads: 1
    out period: 5 sec
    out threads: 4
Content Repository:
  content claim max appendable size: 10 MB
  content claim max flow files: 100
  always sync: false
Provenance Repository:
  provenance rollover time: 1 min
  implementation: org.apache.nifi.provenance.MiNiFiPersistentProvenanceRepository
Component Status Repository:
  buffer size: 1440
  snapshot frequency: 1 min
Security Properties:
  keystore: ''
  keystore type: ''
  keystore password: ''
  key password: ''
  truststore: ''
  truststore type: ''
  truststore password: ''
  ssl protocol: ''
  Sensitive Props:
    key:
    algorithm: PBEWITHMD5AND256BITAES-CBC-OPENSSL
    provider: BC
Processors: []
Controller Services: []
Process Groups:
- id: 75e16bb1-9f3a-3d71-0000-000000000000
  name: MiNiFi PG
  Processors:
  - id: 4a856b63-fbb9-3781-0000-000000000000
    name: TailFile
    class: org.apache.nifi.processors.standard.TailFile
    max concurrent tasks: 1
    scheduling strategy: TIMER_DRIVEN
    scheduling period: 0 sec
    penalization period: 30 sec
    yield period: 1 sec
    run duration nanos: 0
    auto-terminated relationships list: []
    Properties:
      File Location: Local
      File to Tail: FILE_TO_APPEND
      Initial Start Position: Beginning of File
      Rolling Filename Pattern:
      tail-base-directory:
      tail-mode: Single file
      tailfile-lookup-frequency: 10 minutes
      tailfile-maximum-age: 24 hours
      tailfile-recursive-lookup: 'false'
  Controller Services: []
  Process Groups: []
  Input Ports: []
  Output Ports: []
  Funnels: []
  Connections:
  - id: 0bcde547-6377-31a3-0000-000000000000
    name: TailFile/success/NIFI_PORT_ID
    source id: 4a856b63-fbb9-3781-0000-000000000000
    source relationship names:
    - success
    destination id: NIFI_PORT_ID
    max work queue size: 10000
    max work queue data size: 1 GB
    flowfile expiration: 0 sec
    queue prioritizer class: ''
  Remote Process Groups:
  - id: 5cca0411-7d4e-3e0b-0000-000000000000
    name: ''
    url: http://NIFI_SERVER:8080/nifi
    comment: ''
    timeout: 30 sec
    yield period: 10 sec
    transport protocol: RAW
    proxy host: ''
    proxy port: ''
    proxy user: ''
    proxy password: ''
    local network interface: ''
    Input Ports:
    - id: NIFI_PORT_ID
      name: From MiNiFi
      comment: ''
      max concurrent tasks: 1
      use compression: false
      Properties: # Deviates from spec and will later be removed when this is autonegotiated      
          Port: NIFI_SERVER_PORT      
          Host Name: NIFI_SERVER
    Output Ports: []
Input Ports: []
Output Ports: []
Funnels: []
Connections: []
Remote Process Groups: []
NiFi Properties Overrides: {}
